---
- name: creating a user
  hosts: all
  become: true
  #vars:
  #       user:
  #               - john
  #               - kishore
  vars_files:
          - ./var.yml
  tasks:
          - name: creating a user {{ user }}
            user:
                    name: "{{ user }}"


