---
- name: uninstalling the httpd service
  hosts: all
  become: true
  tasks:
          - name: stopping the httpd service on redhat
            service:
                    name: httpd
                    state: stopped
            when: ansible_os_family == "RedHat"

          - name: stopping the apache2 service on ubuntu
            service:
                    name: apache2
                    state: stopped
            when: ansible_os_family == "Debian"

          - name: uninstalling the httpd service
            yum: 
                    name: httpd
                    state: removed
            when: ansible_os_family == "RedHat"

          - name: uninstalling the apache2 service
            apt:
                    name: apache2
                    state: absent
            when: ansible_os_family == "Debian"
