---
# handlers file for kishore
          - name: start the httpd service
            service:
                    name: httpd
                    state: started

          - name: start the apache2 service
            service:
                    name: apache2
                    state: started

          - name: restart the httpd service
            service:
                    name: httpd
                    state: restarted

          - name: restart the apache2 service
            service:
                    name: apache2
                    state: restarted

